filter:
  excluded_paths: [node_modules/*, build/*, lib/*, test/*]

build:
  environment:
    node: v11.7
  dependencies:
    before:
      - npm install && npm run build
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
    coverage:
      tests:
        override:
          - command: npm run report-codecov
            coverage:
              file: "./build/coverage/coverage.lcov"
              format: "lcov"
