filter:
  excluded_paths: [node_modules/*, build/*, lib/*, test/*]

build:
  environment:
    node: v11.7
  dependencies:
    before:
      - yarn install && yarn build
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
