filter:
  excluded_paths: [node_modules/*, build/*, lib/*, test/*]

build:
  environment:
    node: v11.7
    variables:
      NODE_ENV: "prod"
  dependencies:
    before:
      - npm install && npm run build
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
