version: '1.0.0'
services:
  app:
    build: .
    environment:
      - PORT=8080
      - NODE_ENV=dev
      - ENV_NAME=local
      - EXPRESS_PORT=9080
    ports:
      - "8080:8080"
    volumes:
- ./src:/opt/app/src